//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaSW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CUSTOMER_FB
    {
        public Nullable<int> id_persona { get; set; }
        public System.DateTime fdbDate { get; set; }
        public int rating { get; set; }
        public string comment { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
    }
}
