//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaSW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SW_REQUEST
    {
        public int id_request { get; set; }
        public int id_persona { get; set; }
        public string description { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }
        public SW_REQUEST()
        {
        }
        public SW_REQUEST(int id_request, int id_persona, string description)
        {
            this.id_request = id_request;
            this.id_persona = id_persona;
            this.description = description;
        }
    }
}
