//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CasaSW.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USER
    {
        public int id_user { get; set; }
        public Nullable<int> id_persona { get; set; }
        public int denied { get; set; }
        public string phoneN { get; set; }
        public System.DateTime signUpDate { get; set; }
        public string adminFB { get; set; }
    
        public virtual PERSONA PERSONA { get; set; }

        public USER()
        {
        }
        public USER(int id_user, int? id_persona, int denied, string phoneN, DateTime signUpDate, string adminFB)
        {
            this.id_user = id_user;
            this.id_persona = id_persona;
            this.denied = denied;
            this.phoneN = phoneN;
            this.signUpDate = signUpDate;
            this.adminFB = adminFB;
        }
    }
}
